name: Setup Python Environment (Core)
description: Sets up Python with uv and creates a virtual environment

runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"
    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"
    - name: Create virtual environment
      run: |
        uv venv
      shell: bash
