name: Set Package Name
description: Sets the PACKAGE_NAME environment variable by replacing hyphens with underscores in the repository name.

runs:
  using: composite
  steps:
    - name: Set package name
      run: |
        REPO_NAME="${{ github.event.repository.name }}"
        echo "PACKAGE_NAME=${REPO_NAME//-/_}" >> $GITHUB_ENV
        echo "FRONTEND_PACKAGE_NAME=${REPO_NAME}-frontend" >> $GITHUB_ENV
      shell: bash
