name: Run CI job - Pytest
description: Run Pytest tests with coverage reporting.

runs:
  using: composite
  steps:
      - uses: ./.github/actions/setup/install-python-dev
        if: github.event.repository.name == 'template-python'
      - uses: javidahmed64592/template-python/.github/actions/setup/install-python-dev@main
        if: github.event.repository.name != 'template-python'

      - name: Test with pytest
        run: |
          uv run -m pytest --cov-report html --cov-report term
        shell: bash

      - name: Upload backend coverage report
        uses: actions/upload-artifact@v7
        with:
          name: backend-coverage-report
          path: htmlcov
