name: Run CI job - Pip Audit
description: Run pip-audit to check for known vulnerabilities in dependencies.

runs:
  using: composite
  steps:
      - uses: ./.github/actions/setup/install-python-dev
        if: github.event.repository.name == 'template-python'
      - uses: javidahmed64592/template-python/.github/actions/setup/install-python-dev@main
        if: github.event.repository.name != 'template-python'

      - name: Audit dependencies
        run: |
          uv run pip-audit --desc
        shell: bash
