name: Install Core Python Dependencies
description: Installs core Python dependencies from pyproject.toml using uv.

runs:
  using: composite
  steps:
    - uses: actions/checkout@v6
    - uses: ./.github/actions/setup/setup-uv-python
      if: ${{ github.repository == 'javidahmed64592/template-python' }}
    - uses: javidahmed64592/template-python/.github/actions/setup/setup-uv-python@main
      if: ${{ github.repository != 'javidahmed64592/template-python' }}

    - name: Install dependencies
      run: |
        uv sync
      shell: bash
