name: Run CI job - Ruff
description: Run Ruff linting checks on the codebase.

runs:
  using: composite
  steps:
      - uses: actions/checkout@v4
      - uses: javidahmed64592/template-python/.github/actions/setup/install-python-dev@main

      - name: Check with ruff
        run: |
          uv run -m ruff check
        shell: bash
