name: Run CI job - Ruff
description: Run Ruff linting checks on the codebase.

runs:
  using: composite
  steps:
      - uses: ./.github/actions/setup/install-python-dev
        if: github.event.repository.name == 'template-python'
      - uses: javidahmed64592/template-python/.github/actions/setup/install-python-dev@main
        if: github.event.repository.name != 'template-python'

      - name: Check with ruff
        run: |
          uv run -m ruff check
        shell: bash
