name: Run CI job - Validate pyproject.toml
description: Validate pyproject.toml structure.

runs:
  using: composite
  steps:
      - uses: ./.github/actions/setup/install-python-dev
        if: github.event.repository.name == 'template-python'
      - uses: javidahmed64592/template-python/.github/actions/setup/install-python-dev@main
        if: github.event.repository.name != 'template-python'

      - name: Validate pyproject.toml
        run: |
          uv run validate-pyproject pyproject.toml
        shell: bash
