name: Run CI job - Validate pyproject.toml
description: Validate pyproject.toml structure.

runs:
  using: composite
  steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup/install-python-dev
        if: ${{ github.repository == 'javidahmed64592/template-python' }}
      - uses: javidahmed64592/template-python/.github/actions/setup/install-python-dev@main
        if: ${{ github.repository != 'javidahmed64592/template-python' }}

      - name: Validate pyproject.toml
        run: |
          uv run validate-pyproject pyproject.toml
        shell: bash
