name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PACKAGE_NAME: template_python

jobs:
  build-wheel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: javidahmed64592/template-python/.github/actions/build/build-wheel@main

  verify-structure:
    runs-on: ubuntu-latest
    needs: build-wheel
    steps:
      - uses: actions/checkout@v4
      - uses: javidahmed64592/template-python/.github/actions/build/verify-structure@main
