name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-wheel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/build/build-wheel
        if: github.event.repository.name == 'template-python'
      - uses: javidahmed64592/template-python/.github/actions/build/build-wheel@main
        if: github.event.repository.name != 'template-python'

  verify-structure:
    runs-on: ubuntu-latest
    needs: build-wheel
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/build/verify-structure
        if: github.event.repository.name == 'template-python'
      - uses: javidahmed64592/template-python/.github/actions/build/verify-structure@main
        if: github.event.repository.name != 'template-python'
