name: Run CI job - Mypy
description: Run Mypy type checking on the codebase.

runs:
  using: composite
  steps:
      - uses: ./.github/actions/setup/install-python-dev
        if: github.event.repository.name == 'template-python'
      - uses: javidahmed64592/template-python/.github/actions/setup/install-python-dev@main
        if: github.event.repository.name != 'template-python'

      - name: Check with mypy
        run: |
          uv run -m mypy .
        shell: bash
