name: Run CI job - Mypy
description: Run Mypy type checking on the codebase.

runs:
  using: composite
  steps:
      - uses: actions/checkout@v6
      - uses: javidahmed64592/template-python/.github/actions/setup/install-python-dev@main

      - name: Check with mypy
        run: |
          uv run -m mypy .
        shell: bash
